Fixed PostgreSQL build in GitLab CI

diff --git a/mod/mod-01-05/mod-01-05-docker_bundle_install b/mod/mod-01-05/mod-01-05-docker_bundle_install
--- a/mod/mod-01-05/mod-01-05-docker_bundle_install
+++ b/mod/mod-01-05/mod-01-05-docker_bundle_install
@@ -1,12 +1,23 @@
 #!/bin/bash
 set +e
 
-# NOTE: /home/winner/myapp/tmp/bundle is the BUNDLE_PATH directory specified in docker-compose.yml
-echo '----------------------------------------------------------------------------------------------'
-echo 'mkdir -p /home/winner/myapp/tmp/bundle && chown -R winner:winner /home/winner/myapp/tmp/bundle'
-docker-compose run --rm -u root web bash -c 'mkdir -p /home/winner/myapp/tmp/bundle && chown -R winner:winner /home/winner/myapp/tmp/bundle'
+APP_PATH='/home/winner/myapp'
 
-set -e
+# Set permissions
+# NOTE: Skipping this step in the GitLab CI setup results in permission issues
+chown_dir () {
+  DIR_TO_CHOWN=$1
+  echo '--------------------------------------------------------------'
+  echo "mkdir -p $DIR_TO_CHOWN && chown -R winner:winner $DIR_TO_CHOWN"
+  docker-compose run --rm -u root web bash -c "mkdir -p $DIR_TO_CHOWN && chown -R winner:winner $DIR_TO_CHOWN"
+}
+
+chown_dir "$APP_PATH"
+
+# NOTE: set -o pipefail is needed to ensure that any error or failure causes the whole pipeline to fail.
+# Without this specification, the CI status will provide a false sense of security by showing builds
+# as succeeding in spite of errors or failures.
+set -eo pipefail
 
 docker/gem_install_bundler
 
diff --git a/mod/mod-02-04/mod-02-04-docker_rbp b/mod/mod-02-04/mod-02-04-docker_rbp
--- a/mod/mod-02-04/mod-02-04-docker_rbp
+++ b/mod/mod-02-04/mod-02-04-docker_rbp
@@ -1,6 +1,9 @@
 #!/bin/bash
 
-set -e
+# NOTE: set -o pipefail is needed to ensure that any error or failure causes the whole pipeline to fail.
+# Without this specification, the CI status will provide a false sense of security by showing builds
+# as succeeding in spite of errors or failures.
+set -eo pipefail
 
 # Checks the quality of Rails code, not recommended for legacy apps
 echo '----------------------------------'
diff --git a/mod/mod-02-05/mod-02-05-bin-sandi_meter b/mod/mod-02-05/mod-02-05-bin-sandi_meter
--- a/mod/mod-02-05/mod-02-05-bin-sandi_meter
+++ b/mod/mod-02-05/mod-02-05-bin-sandi_meter
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+# NOTE: set -o pipefail is needed to ensure that any error or failure causes the whole pipeline to fail.
+# Without this specification, the CI status will provide a false sense of security by showing builds
+# as succeeding in spite of errors or failures.
+set -eo pipefail
+
 docker/replace_sif "# gem 'sandi_meter'" "gem 'sandi_meter'" 'Gemfile'
 
 echo '----------------------'
